version: '3'

services:
  rmq:
    ports:
      - "5672:5672"

volumes:
  configs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/rp_project/rp_static/configs'
