version: "3"
services:
  r1:
    build: rp_static
    image: rp_static
    networks:
      - rp_network
    environment:
      config_name: r1.config
    volumes:
      - configs:/usr/src/app/configs
  r2:
    image: rp_static
    networks:
      - rp_network
    environment:
      config_name: r2 .config
    volumes:
      - configs:/usr/src/app/configs
  rmq:
    image: rabbitmq:3.7.8-alpine
    networks:
      - rp_network
networks:
  rp_network:
volumes:
  configs:
