---
hostname: R1

protocols:
  rip:
    interfaces:
      - E0
      - E1
  static:
    10.1.8.0/24: 10.1.1.8
    10.8.0.0/24: 10.1.8.2

interfaces:
  E0:
    ipaddr: 10.0.1.1/24
  E1:
    ipaddr: 10.0.1.2/24
  E2:
    ipaddr: 10.1.1.1/24





