---
hostname: R2


protocols:
  rip:
    interfaces:
      - E0
      - E1

interfaces:
  E0:
    ipaddr: 10.0.1.3/24
  E1:
    ipaddr: 10.1.1.2/24
  E2:
    ipaddr: 10.0.3.1/30
  E3:
    ipaddr: 10.0.4.1/30
